FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

EXPOSE 8000 8001

# Define the command to start the container
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 & flask run --host 0.0.0.0 --port 8001"]